Add files via upload
StrawberryPick/Strawberry pull request #55
Opened 2021-11-17 14:34 UTC by HerzogX

Data Infrastructure Flow UML

2021-11-17 15:14 UTC, ViklaSail requested changes
Please remove spaces of the filename

2021-11-18 12:11 UTC, Altti99 approved these changes

2021-11-18 12:11 UTC, Altti99 commented
ok

2021-11-18 12:11 UTC, Altti99 approved these changes

2021-11-18 12:16 UTC, Altti99 approved these changes

2021-11-19 14:52 UTC, merged